[package]
name = "egsolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
egg = "0.7.1"
pest = "2.1"
pest_derive = "2.1"
